# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
    -   id: php-lint
        files: \.(php)$
        exclude: |
            (?x)^(
                (.*blade\.php)|
                (.*public\/index.php)|
                (.*resources\/lang.*)
            )$
    -   id: php-cbf
        files: \.(php)$
        exclude: |
            (?x)^(
                (.*blade\.php)|
                (.*public\/index.php)|
                (.*resources\/lang.*)
            )$
        args: [--standard=PSR12 -p]
    -   id: php-cs
        files: \.(php)$
        exclude: |
            (?x)^(
                (.*blade\.php)|
                (.*public\/index.php)|
                (.*resources\/lang.*)
            )$
        args: [--standard=PSR12 -p]
-   repo: https://github.com/hadolint/hadolint
    rev: master
    hooks:
      - id: hadolint-docker
