version: '3.8'
services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - laravel-storage:/var/www/storage
            - ./docker/app/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        environment:
            APP_NAME: ${APP_NAME}
            APP_ENV: ${APP_ENV}
            APP_KEY: ${APP_KEY}
            APP_DEBUG: ${APP_DEBUG}
            APP_URL: ${APP_URL}
            APP_TIMEZONE: ${APP_TIMEZONE}
            APP_LOCALE: ${APP_LOCALE}
            STEAM_API_KEY: ${STEAM_API_KEY}
            GOOGLE_API_KEY: ${GOOGLE_API_KEY}
            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            CACHE_DRIVER: ${CACHE_DRIVER}
            SESSION_DRIVER: ${SESSION_DRIVER}
            SESSION_LIFETIME: ${SESSION_LIFETIME}
            LOG_CHANNEL: ${LOG_CHANNEL}
        networks:
            - app-network
        depends_on:
            - db
        labels:
            ofelia.enabled: "true"
            ofelia.job-exec.artisan-schedule-run.schedule: "@every 1m"
            ofelia.job-exec.artisan-schedule-run.command: "php /var/www/artisan schedule:run"
    scheduler:
        image: mcuadros/ofelia:latest
        container_name: scheduler
        depends_on:
            - app
        command: daemon --docker
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/webserver/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
        depends_on:
            - app
    db:
        image: mysql:8
        container_name: db
        restart: unless-stopped
        tty: true
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
            - ./docker/db/mysql/conf.d:/etc/mysql/conf.d
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    db-data:
        driver: local
    laravel-storage:
        driver: local
